<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <UserSecretsId>17df84b2-8577-4b61-b466-e04c093bb95f</UserSecretsId>
    </PropertyGroup>
</Project>
