<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="NodaTime" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="Testably.Abstractions.FileSystem.Interface" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SendHub\SendHub.csproj" />
    </ItemGroup>

    <ItemGroup>
        <internalsVisibleTo Include="SendHub.Infrastructure.Tests"/>
        <internalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>
    
</Project>
